### ISSUE TITLE
Replies to myself discarded

### ISSUE THREAD

**Issue by bitoclass** [marcomaroni-github/twitter-to-bluesky#102]
I can see various issues relating to this have been raised before but I can't figure out whether they are all meant to be resolved now or not and couldn't see anything identical to this, so forgive me for raising it if it's a duplicate!

I've been running an import for a week now (so I'm on whatever version was current as at last Saturday). I have noticed sometimes when looking at the account I'm importing to that a tweet appears which looks like it should become a thread, but it doesn't. I think all the replies to myself are being discarded.

I found a concrete example of this today - here's an extract from the log:

> Parse tweet id '658071249101418497'
 Created at 2015-10-25T00:03:06.000Z
 Full text 'I was just vaguely thinking about an arty/puzzly thing you could do with the repeated hour tonight…'
{
  '$type': 'app.bsky.feed.post',
  text: 'I was just vaguely thinking about an arty/puzzly thing you could do with the repeated hour tonight…',
  facets: undefined,
  createdAt: '2015-10-25T00:03:06.000Z'
}
Bluesky post create, URL: https://bsky.app/profile/twitter.bitoclass.uk/post/3lbjuwf57ay27
Parse tweet id '658071565007998976'
 Created at 2015-10-25T00:04:22.000Z
 Full text '…but it involved scheduling tweets across both hours and I'm really not sure how TweetDeck would handle that. So I'll just go to sleep then.'
Discarded (reply to self in aother user's thread)

That is not a reply from another user's thread, that's just a simple reply to myself, so it shouldn't have been discarded.

I have a few questions:

1. Is this a known bug which has already been fixed, so if I upgraded to a new release it wouldn't happen any more?
2. If so, is it OK to stop the process running, do an upgrade, then run the process again? I saw something about this not being a problem because progress was stored in the "tweets_mapping.json" file - but there is no such file in my project folder.
3. How can I fill the gaps of all the replies to myself that have been discarded so far? Could a new .env parameter be added which could tell the program to **only** import replies to myself, or something? That way I could just leave it running for now, then run the process again with that parameter set afterwards to fill all the gaps.

Would welcome any advice/feedback about any of this.

Thanks so much for building this importer, it's fantastic!

**Comment by marcomaroni-github** [comment]
>Is this a known bug which has already been fixed, so if I upgraded to a new release it wouldn't happen any more?

Try with the latest release

>If so, is it OK to stop the process running, do an upgrade, then run the process again? I saw something about this not being a problem because progress was stored in the "tweets_mapping.json" file - but there is no such file in my project folder.

Point 3 at the moment this thing is not managed

**Comment by bitoclass** [comment]
> The file is created when the process is terminated.

Ah, thanks for clarifying this! Unfortunately the computer rebooted itself earlier this week while the process was running, so presumably now I will never get a JSON file created for the first few days of the import?

I'll stop the process when it reaches today's rate limit, upgrade the importer to the latest release, and resume it tomorrow using the from date env parameter, and see if it imports replies to myself OK from that point on. I guess then the only way to fill the gaps would be to delete the Bluesky account I've been importing to and start again? 🤔

Thanks again!

**Comment by bitoclass** [comment]
The process had crashed today so I took the opportunity to upgrade and resume from the date it had got to. It is now correctly importing replies to myself!

This leaves me with around 500 replies to myself between February 2014 and May 2016 which have not been imported. If anyone has any suggestions on how I could import any tweet between those dates which has `"in_reply_to_user_id": "15183948"` but no other tweets between those dates, I would love to fill those gaps.

Thanks for your help and thanks again for this great tool!

P.S. Is there an 'official' way to stop the importer running cleanly (on Windows)? I just killed it through Task Manager as I couldn't find any other way to do this.

**Comment by bitoclass** [comment]
Update: I managed to use Excel to filter down the IDs of the 18,000 tweets in that period which **weren't** replies to myself, then space-separated those and put them into the IGNORE_TWEET_IDS parameter and ran the importer for that period of time using MIN_DATE and MAX_DATE.

Your incredible importer appears to be coping fine with 18,000 space-separated IDs to ignore and is now importing all the missing replies. Amazing!

**Comment by marcomaroni-github** [comment]
> P.S. Is there an 'official' way to stop the importer running cleanly (on Windows)? I just killed it through Task Manager as I couldn't find any other way to do this.

On Windows CTRL+C
