### ISSUE TITLE
Post dates not correcting

### ISSUE THREAD

**Issue by FernsDC** [marcomaroni-github/twitter-to-bluesky#104]
I saw in the doc that posts may come in with the current date, but will self-correct:
"Some of the tweets may show up as recent posts on your BlueSky timeline during the import process... their date gets corrected in a couple of minutes. No need to worry about this. Issue #97."

The dates were fine at the start, but now they are showing up as recent, and not correcting, even after a day. 

Bluesky is showing this at the bottom of the posts:
_"Archived from August 6, 2015 at 8:06 PM
November 24, 2024 at 7:49 AM"_  
-https://bsky.app/profile/fernss.bsky.social/post/3lbnekpmsre25

The first line is clickable & shows this message:
_"Archived post
This post claims to have been created on August 6, 2015 at 8:06 PM, but was first seen by Bluesky on November 24, 2024 at 7:49 AM.
Bluesky cannot confirm the authenticity of the claimed date."_

FWIW, I have a huge archive (from 2010). Dates were correct up until 2013 (I've not been watching it & am unsure how to find when it started doing this), but now they're all posting like this.

I stopped the import for the moment.

Any ideas?

Thanks

**Edited to add**: 
I figured out how to go right back to the very first imported tweet, and the very first one in the import ALSO looks like this (https://bsky.app/profile/fernss.bsky.social/post/3lbj3gyvoqo2h). 

Then I checked my test account where I only did a partial import (https://bsky.app/profile/ffscomeon.bsky.social ) and they look like this also. They 100% all showed up with the original date as the post date when I did the test or I'd have asked this question then. 

The real import also definitely started as expected with the original date being the post date (one of my followers even commented that it was weird to see the huge time gap between 2013 posts and now). 

Could it be that bsky is going back to mark old imported tweets like this?

**Comment by tibor** [comment]
https://bsky.app/profile/bsky.app/post/3lbdnmbcx7s2u

**Comment by FernsDC** [comment]
Oh! Thanks so much for that.

**Comment by FernsDC** [comment]
Forgot to close it...

**Comment by Lucifer-is-my-pet** [comment]
found the feature request for changing the way the dates are applied https://github.com/bluesky-social/social-app/issues/6707
I hope it won't be discarded

**Comment by FernsDC** [comment]
> found the feature request for changing the way the dates are applied [bluesky-social/social-app#6707](https://github.com/bluesky-social/social-app/issues/6707) I hope it won't be discarded

Thanks so much for the link.

I raised it via a message to them, thinking it was a bug: It appears it isn't. Glad to see someone has raised it more formally.
