### ISSUE TITLE
Type 'ArrayBuffer | Buffer<ArrayBufferLike>' is not assignable to type 'ArrayBuffer'

### ISSUE THREAD

**Issue by nawanawa** [marcomaroni-github/twitter-to-bluesky#110]
Hey there! I've downloaded the latest release, set up the .env file and launched the script with `npm start`, and it prompted me to install TypeScript: 
```
Need to install the following packages:
tsc@2.0.4
Ok to proceed? (y)
```
I agreed but npm asked me to use `npm install typescript` instead, so I did that. After that, I'm getting this error:

```
app.ts:473:7 - error TS2322: Type 'ArrayBuffer | Buffer<ArrayBufferLike>' is not assignable to type 'ArrayBuffer'.
  Type 'Buffer<ArrayBufferLike>' is missing the following properties from type 'ArrayBuffer': maxByteLength, resizable, resize, detached, and 2 more.

473       return imgBuffer;
          ~~~~~~

app.ts:531:9 - error TS2322: Type 'ArrayBuffer | Buffer<ArrayBufferLike>' is not assignable to type 'ArrayBuffer'.
  Type 'Buffer<ArrayBufferLike>' is missing the following properties from type 'ArrayBuffer': maxByteLength, resizable, resize, detached, and 2 more.

531         return imgBuffer;
            ~~~~~~

app.ts:562:7 - error TS2322: Type 'ArrayBufferLike' is not assignable to type 'ArrayBuffer'.
  Type 'SharedArrayBuffer' is missing the following properties from type 'ArrayBuffer': resizable, resize, detached, transfer, transferToFixedLength

562       return strippedBuffer.buffer;
          ~~~~~~

app.ts:569:7 - error TS2322: Type 'ArrayBuffer | Buffer<ArrayBufferLike>' is not assignable to type 'ArrayBuffer'.
  Type 'Buffer<ArrayBufferLike>' is missing the following properties from type 'ArrayBuffer': maxByteLength, resizable, resize, detached, and 2 more.

569       return imgBuffer;
          ~~~~~~
```

I'm running node v22.2.0, npm v10.7.0, Windows 11 24H2. Let me know if I need to provide any other info.

**Comment by EfriNS** [comment]
Getting the same errors here (Windows 11, used the command line, with --simulate)

**Comment by epicEaston197** [comment]
I thought i was doing something wrong it's good to know that I'm not the only one that's encountering this issue on windows 11

**Comment by marcomaroni-github** [comment]
As soon as I can I'll try to simulate with those versions of node and typescript

**Comment by epicEaston197** [comment]
> As soon as I can I'll try to simulate with those versions of node and typescript

So my friend actually fixed it entirely they gave me their version and it ran without any issues after I created a proper `.env` file
I've asked if they would make a pull request and haven't got a response yet they will probably make one

**Comment by epicEaston197** [comment]
> I'm not sure if this is the same change your friend made @epicEaston197 ?

I'm not sure either
