### ISSUE TITLE
Imported replies are not threaded properly

### ISSUE THREAD

**Issue by b02860de585071a2** [marcomaroni-github/twitter-to-bluesky#26]
When I perform an import (using `BLUESKY_USERNAME=[REDACTED] BLUESKY_PASSWORD=[REDACTED] ARCHIVE_FOLDER=[/path/to/folder] npm start`), I expect that threaded replies started by myself should follow this structure:

```bash
Original tweet with replies
|
|-Reply 1 (to original tweet)
|-|
|-|-Reply 2 (to Reply 1)
|
|--Reply 3 (to original tweet)
|
| [...]

Another tweet
```

However, they are imported flat (ie all separate bsky posts in reverse chronological order), more like this:

```bash
Reply 3 (to original tweet)

Reply 2 (to Reply 1)

Reply 1 (to original tweet)

Another tweet

Original tweet with replies
```

This might be a misunderstanding on my part, but to my understanding, importing replies *should* keep the original thread structure intact. Is this actually the intended use case? If so, I'd suggest updating the README to be a bit more clear on the functionality.

I have tried this with v0.6.0, v0.7.0-beta.1, and pulling the current dev branch from git directly.

**Comment by wicogohome** [comment]
> In the tests I did, the import of the replicas followed the correct flow (the first one in your example), @wicogohome what do you think?

I also tested and ended up with the correct flow.

@b02860de585071a2 Could you please verify the sequences in your `tweets_mapping.json`? They should be stored in ascending order.(According to created_at)

Also, I'm concerned : Did your bsky posts reply to the correct post?  
Perhaps you can delete the issue posts (both bsky and remove those posts attributes `bsky `in `tweets_mapping.json`), and retry with `npm run start_log`, and then check the API parameters of the bsky in `import.log`; they should include `reply`.

**Comment by b02860de585071a2** [comment]
> @b02860de585071a2 Could you please verify the sequences in your `tweets_mapping.json`? They should be stored in ascending order.(According to created_at)


Sure thing, well check this tomorrow when I get time. I have logs from several runs in one of my project folders.

**Comment by b02860de585071a2** [comment]
Sorry for the late update, long week.

> Could you please verify the sequences in your `tweets_mapping.json`? They should be stored in ascending order.(According to created_at)

Correct, they are.

> Also, I'm concerned : Did your bsky posts reply to the correct post? 

No. They actually didn't reply to anything at all.

> retry with npm run start_log, and then check the API parameters of the bsky in import.log; they should include reply.

Strange behavior from these, there is no "reply" parameter. I'll copy over the relevant parts of the log. This is all being done on a test account with strict date constraints for now, so I can test these pretty easily.


@wicogohome let me know if you need more specific info than this:

<details>
<summary>From `tweets_mapping.json`:</summary>
Original tweet:


    {
        "tweet": {
            "edit_info": {
                "initial": {
                    "editTweetIds": [
                        "[REDACTED]"
                    ],
                    "editableUntil": "[REDACTED]",
                    "editsRemaining": "5",
                    "isEditEligible": false
                }
            },
            "retweeted": false,
            "source": "<a href=\"http://twitter.com/download/android\" rel=\"nofollow\">Twitter for Android</a>",
            "entities": {
                "hashtags": [],
                "symbols": [],
                "user_mentions": [],
                "urls": []
            },
            "display_text_range": [
                "0",
                "273"
            ],
            "favorite_count": "19",
            "id_str": "[REDACTED]",
            "truncated": false,
            "retweet_count": "1",
            "id": "[REDACTED]",
            "created_at": "[REDACTED]",
            "favorited": false,
            "full_text": "[REDACTED]",
            "lang": "en"
        }
    },



First threaded reply:


    {
        "tweet": {
            "edit_info": {
                "initial": {
                    "editTweetIds": [
                        "[REDACTED]"
                    ],
                    "editableUntil": "[REDACTED]",
                    "editsRemaining": "5",
                    "isEditEligible": false
                }
            },
            "retweeted": false,
            "source": "<a href=\"http://twitter.com/download/android\" rel=\"nofollow\">Twitter for Android</a>",
            "entities": {
                "hashtags": [],
                "symbols": [],
                "user_mentions": [],
                "urls": [
                    {
                        "url": "[REDACTED]",
                        "expanded_url": "[REDACTED]",
                        "display_url": "[REDACTED]",
                        "indices": [
                            "72",
                            "95"
                        ]
                    }
                ]
            },
            "display_text_range": [
                "0",
                "95"
            ],
            "favorite_count": "0",
            "in_reply_to_status_id_str": "[REDACTED]",
            "id_str": "[REDACTED]",
            "in_reply_to_user_id": "[REDACTED]",
            "truncated": false,
            "retweet_count": "0",
            "id": "[REDACTED]",
            "in_reply_to_status_id": "[original tweet ID]",
            "possibly_sensitive": false,
            "created_at": "[REDACTED]",
            "favorited": false,
            "full_text": "[REDACTED]",
            "lang": "en",
            "in_reply_to_screen_name": "[me]",
            "in_reply_to_user_id_str": "[REDACTED]"
        }
    },

</details>


<details>
<summary>From `import.log`</summary>
Original tweet:

```
Parse tweet id '[REDACTED]'
 Created at [REDACTED] 
 Full text '[REDACTED]'
{
  '$type': 'app.bsky.feed.post',
  text: '[REDACTED]',
  facets: undefined,
  createdAt: '[REDACTED]'
}
```

First threaded reply:

```
Parse tweet id '[REDACTED]'
 Created at [REDACTED]
 Full text '[REDACTED]'
{
  '$type': 'app.bsky.feed.post',
  text: '[REDACTED]',
  facets: [ { index: [Object], features: [Array] } ],
  createdAt: '[REDACTED]'
}
```
</details>

**Comment by wicogohome** [comment]
> > Also, I'm concerned : Did your bsky posts reply to the correct post?
> 
> No. They actually didn't reply to anything at all.
> 
> Strange behavior from these, there is no "reply" parameter. I'll copy over the relevant parts of the log. This is all being done on a test account with strict date constraints for now, so I can test these pretty easily.
> 

@b02860de585071a2 Thank you for supplying the logs. There are two potential issues:

1. Missing `PAST_HANDLES`: We utilize `PAST_HANDLES `to ensure that we import self-reply (along with img/url replacement). Please add your account to this ENV.  
 (if you have already changed your account name, you should add all of them).

3. Missing `bsky` attributes in 'tweets_mapping.json':I am not sure why this situation occurred. However, we use the original tweet's `bsky` attributes to determine the tweet & bsky post id mapping. That is, the origin tweet should always be imported first. 
For example, if you import duration `10/10~11/10` first, then import `9/10~10/10`, the replies of the first duration can't find the bsky ids of the second duration.Because the parent tweet doesn't import yet.  

Please ensure that when you import the responses, the parent has already been imported.


I think that adding `PAST_HANDLES` and re-importing may solve this issue.  
If it still doesn't work, try `console.log(currentData, recordData) ` after this block and check it. Thanks.
```js
// app.ts
                    // store bsky data into sortedTweets (then write into the mapping file)
                    currentData.bsky = {
                        uri: recordData.uri,
                        cid: recordData.cid,
                    };
```

**Comment by b02860de585071a2** [comment]
> 1. Missing `PAST_HANDLES`: We utilize `PAST_HANDLES `to ensure that we import self-reply (along with img/url replacement). Please add your account to this ENV.  
>  (if you have already changed your account name, you should add all of them).

I actually have done this, including earlier today (as `PAST_HANDLES=[me]` or leaving it empty). This account has never had a username change. 



> For example, if you import duration `10/10~11/10` first, then import `9/10~10/10`, the replies of the first duration can't find the bsky ids of the second duration.Because the parent tweet doesn't import yet.  


Let me make sure I'm understanding this correctly. 

Let's say I have a parent tweet from `2024-10-01`, and a reply from `2024-10-02`. If I import the range `2023-09-30~2024-10-03` (this is what I've been doing), it *should* work, correct?

**Comment by wicogohome** [comment]
> Let's say I have a parent tweet from `2024-10-01`, and a reply from `2024-10-02`. If I import the range `2024-09-30~2024-10-03` (this is what I've been doing), it should work, correct?

Yeah, you are correct. It should be worked.  

Are there any `bsky` attributes in `tweets_mapping.json`?
If not, try copying this file, deleting the original, and then re-importing.

Please also check this information, thanks.
> If it still doesn't work, try console.log(currentData, recordData)  after this block and check it. Thanks.

**Comment by b02860de585071a2** [comment]
..........it was a capitalization issue. `PAST_HANDLES` is apparently case-sensitive, and I didn't capitalize my username :upside_down_face: 

Not sure if this is intended, or just an API limit?

**Comment by marcomaroni-github** [comment]
@b02860de585071a2 Yes I confirm in the code a comparison of test case sensitive is made, it is not an "API" problem.
