### ISSUE TITLE
Short URL resolver issues: Missing User-Agent and handling bad URL texts

### ISSUE THREAD

**Issue by clemensv** [marcomaroni-github/twitter-to-bluesky#37]
The short URL resolver code in (resolveShorURL) has two issues (besides the typo in the name):

a) The request should use common browser User-Agent header since some resolved, including Facebook's, redirect to a "unknown broswer" URL otherwise
b) If the URL embedded in the Tweet is bad, especially if it contains illegal characters, the operation fails and crashes the app.

PR forthcoming

**Comment by marcomaroni-github** [comment]
@clemensv is the point b) related to #20 ?

**Comment by clemensv** [comment]
Likely, yes
