### ISSUE TITLE
Replies to oneself (threads) being discarded

### ISSUE THREAD

**Issue by Draikin** [marcomaroni-github/twitter-to-bluesky#42]
Hi,

I tried using this tool and it works quite nicely! That said I ran into an issue: the replies to oneself (threads) weren't being added for me. I noticed the tweets were discarded since they all started with "@<my-user-handle>", so while it gets past the initial check for replies, they're still discarded because they start with @ (see code below). I got it to work for me by making a change to remove the  "@<my-user-handle>" from tweet.full_text prior to the startswith("@") check afterwards, and the replies were added correctly then. But I'm not sure if maybe I'm missing something here or I made a mistake somewhere, since this was apparently supposed to work?

```                
                if (DISABLE_IMPORT_REPLY && tweet.in_reply_to_screen_name) {
                    console.log("Discarded (reply)");
                    continue;
                }
                if (tweet.full_text.startsWith("@")) {
                    console.log("Discarded (start with @)");
                    continue;
                }
```

**Comment by marcomaroni-github** [comment]
@wicogohome If you can, try to take a look at this fix too, if it works for you.

**Comment by marcomaroni-github** [comment]
@Draikin I have committed your proposed modification in this branch, aligning it with the existing code, tell me if it seems ok to you
