### ISSUE TITLE
images not uploaded

### ISSUE THREAD

**Issue by schlazor** [marcomaroni-github/twitter-to-bluesky#43]
Great script! Appreciate the work you've done! I ran it on my archive today and it seems like it's only including links to images rather than actually uploading them? Is that expected? Or are there circumstances in which it chooses to do that? I checked the archive and the images are definitely there.

**Comment by marcomaroni-github** [comment]
Hi @schlazor all images present in the archive and present in the original tweets should be uploaded with the posts on Bluesky.

**Comment by clemensv** [comment]
this "break;" is getrting in teh way: https://github.com/marcomaroni-github/twitter-to-bluesky/blame/42c7f469cec0e00d7183260ac5e9a5dce6d28b40/app.ts#L275

**Comment by marcomaroni-github** [comment]
I should have fixed it in the latest [version](https://github.com/marcomaroni-github/twitter-to-bluesky/releases/tag/v0.7.4). Let me know @clemensv and @schlazor

**Comment by schlazor** [comment]
thank you both!
