### ISSUE TITLE
replies to yourself when the parent tweet is someone else's are included

### ISSUE THREAD

**Issue by schlazor** [marcomaroni-github/twitter-to-bluesky#47]
It's good that replies to yourself are included so threads work, but I think it also needs to check if the handle that starts the reply text matches the `in_reply_to_screen_name` and exclude if not

**Comment by marcomaroni-github** [comment]
@schlazor  Latest version 0.8 it does exactly the check you say.
See https://github.com/marcomaroni-github/twitter-to-bluesky/commit/cc8c788404a0b06a1c75191b8573e81c71e516f3

**Comment by schlazor** [comment]
> @schlazor Latest version 0.8 it does exactly the check you say. See [cc8c788](https://github.com/marcomaroni-github/twitter-to-bluesky/commit/cc8c788404a0b06a1c75191b8573e81c71e516f3)

Almost!! See PR above
