### ISSUE TITLE
"twitter-handles" seems to be case sensitive

### ISSUE THREAD

**Issue by ffylin** [marcomaroni-github/twitter-to-bluesky#83]
None of my replies to own tweets (threads) were imported. In the terminal, I can see all these replies, but they all said:
> Discarded (reply to another user)

After some testing, it appears that the issue is “twitter-handles” being case sensitive. Is this the desired behavior? If so, I’d suggest that it’s specified it in the README.

**Comment by marcomaroni-github** [comment]
Done, thanks!
